project:
  type: website
  output-dir: _site

website:
  title: "Jing Lab"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: People
        href: people.qmd
      - text: Research
        menu:
          - href: research/index.qmd
          - text: Long-Term Change
            href: research/long-term.qmd
          - text: Plant Phenology
            href: research/phenology.qmd
          - text: Species Invasions
            href: research/invasions.qmd
      - text: Publications
        href: publications.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Join us
        href: join-us.qmd
      - text: Values
        href: values.qmd
      - text: Blog
        href: blog/index.qmd
    right:
      - icon: github
        href: https://github.com/jiaojiaojing
      - text: CV
        href: files/CV.pdf
  page-footer:
    left: |
      © the Jing Lab 2020–{{< meta year >}}
    right: |
      Last change: {{< meta today >}}
format:
  html:
    theme:
      - flatly
      - custom.scss
    toc: false
    smooth-scroll: true
    anchor-sections: true
execute:
  freeze: auto
