project:
  type: website
  output-dir: _site

website:
  title: "Jing Lab"
  favicon: images/favicon.png  # optional – replace with your own if desired

  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: People
        href: people.qmd
      - text: Research
        menu:
          - text: Overview
            href: research/index.qmd
          - text: Topics
            href: research/topics.qmd
          - text: Publications
            href: publications.qmd
          - text: Software
            href: software.qmd
      - text: Teaching
        href: teaching.qmd
      - text: News
        href: news.qmd
      - text: Join us
        href: join-us.qmd
      - text: Values
        href: values.qmd
    right:
      - text: CV
        href: files/CV.pdf
      - icon: github
        href: https://github.com/jiaojiaojing

  page-footer:
    left: "© Jing Lab"
    right: "Last change: {{< modified '%Y/%m/%d' >}}"

  search: true

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: false
    anchor-sections: true
    smooth-scroll: true
    page-layout: article
    code-copy: true
    link-external-newwindow: true

page-navigation: true
